org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,neoforge
## Mod Properties
archives_name=horseman
mod_id=horseman
mod_name=Horseman
mod_version=1.7.4
mod_release_type=release
mod_license=MIT
mod_maven_group=io.github.mortuusars.horseman
mod_authors=mortuusars
mod_description=Improved horses: faster hitching, smooth riding, QOL features and more.
mod_page=https://www.curseforge.com/minecraft/mc-mods/horseman
mod_github=https://github.com/mortuusars/Horseman
mod_issues=https://github.com/mortuusars/Horseman/issues
mod_curseforge_project_id=1082085
mod_modrinth_project_id=qIv5FhAA
# Minecraft properties
minecraft_version=26.1.1
minecraft_version_range=[26.1,26.2)
supported_minecraft_versions=26.1,26.1.1,26.1.2
# Fabric
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
fabric_supported_minecraft_versions=26.1.x
# NeoForge
neoforge_version=26.1.1.2-beta
neoforge_version_range=[26.1,26.2)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=26.1.3
required_forge_config_api_port_version=26.1
jupiterVersion=5.11.3
# Mod Versions
jei_version=29.3.0.22
jade_version=26.0.8
